### ISSUE TITLE
Improve GTK 2 Support

### ISSUE THREAD

**Issue by TicTac7x** [Xenite/Xenite#40] opened 2015-04-22 19:02 UTC
![ekraanipilt 2015-04-22 21 57 32](https://cloud.githubusercontent.com/assets/7373586/7282822/3a8f6e26-e93b-11e4-8d84-2eaf6d40cb75.png)

Maybe should look like this:
![ekraanipilt 2015-04-22 22 02 50](https://cloud.githubusercontent.com/assets/7373586/7282853/5c9bcd66-e93b-11e4-9873-ecb7b8aa8cb5.png)

**Comment by Defman21** [comment] 2015-04-22 19:03
Looks fine to me. Are you sure that you installed gtk2-engines-pixbuf and murrine?

**Comment by Defman21** [comment] 2015-04-22 19:11
@crutchcorn can you reproduce to that?

**Comment by crutchcorn** [comment] 2015-04-22 19:13
What application is the top one?

**Comment by Defman21** [comment] 2015-04-22 19:14
It seems to be a default file picker. Just click on the "selecting them" link in the "Write" pane on GitHub.

**Comment by TicTac7x** [comment] 2015-04-22 19:16
You are correct, I installed the pixbuf and murrine and here's what i get:
![ekraanipilt 2015-04-22 22 13 43](https://cloud.githubusercontent.com/assets/7373586/7283128/ff0e69d6-e93c-11e4-8c43-6cff58ffd832.png)


Still, they don't look quite the same, maybe make them look the same, or at least try to make them look the same.

Also maybe include the note you need to install gtk2-engines-pixbuf and gtk2-engines-murrine? I didn't know that.

**Comment by crutchcorn** [comment] 2015-04-22 19:17
He is right though, it should look a bit different to match the rest. @TicTac7x, I didn't have to install anything.

**Comment by Defman21** [comment] 2015-04-22 19:19
I'll try to improve the style but not now, it's rendered through GTK2 and I don't have a time to learning GTK2 shits now.

**Comment by crutchcorn** [comment] 2015-04-22 19:23
I might be able to do something Thursday and Friday night

**Comment by Defman21** [comment] 2016-07-26 13:34
@crutchcorn I suppose you're not interested in the developing anymore?

**Comment by crutchcorn** [comment] 2016-07-26 13:35
I'm alive. :P

**Comment by Defman21** [comment] 2016-07-26 13:37
That's great :)
I'll assign that for myself since I'll make the theme using the default theme with some changes in it.

**Comment by vinctux** [comment] 2016-07-26 14:05
@Defman21 @crutchcorn Nice to hear from both of you again. I updated [`themeon`](https://github.com/vinctux/themeon) to [v1.3](https://github.com/vinctux/themeon/releases/tag/v1.3), also pushed the changes to `Xenite`'s `master`, so it should now support system-wide and user-wide theme install. I hope it'll work now as expected :smile: 

@crutchcorn BTW, I wanted to ask if I should open up a PR with `themeon` for your [`chromeostheme`](https://github.com/crutchcorn/chromeostheme)? I would be glad if the setup scripts would help the management for some other themes too ;)

**Comment by Defman21** [comment] 2016-07-28 21:31
I'm going to close it in favor of #72

**Closed by Defman21** 2016-07-28 21:31 UTC
Labels: enhancement
